<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2026 Philip Helger (www.helger.com)
    philip[at]helger[dot]com

    Forked from samdjstevens/java-totp (Sam Stevens, MIT License); see NOTICE.txt.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.helger</groupId>
    <artifactId>parent-pom</artifactId>
    <version>3.1.0</version>
  </parent>
  <artifactId>ph-totp-parent-pom</artifactId>
  <version>2.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>ph-totp-parent-pom</name>
  <description>Base POM to build the ph-totp projects</description>
  <url>https://github.com/phax/ph-totp</url>
  <inceptionYear>2026</inceptionYear>

  <licenses>
    <license>
      <name>Apache 2</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:https://github.com/phax/ph-totp.git</connection>
    <developerConnection>scm:git:https://github.com/phax/ph-totp.git</developerConnection>
    <url>https://github.com/phax/ph-totp</url>
    <tag>HEAD</tag>
  </scm>

  <organization>
    <name>Philip Helger</name>
    <url>https://www.helger.com</url>
  </organization>

  <developers>
    <developer>
      <id>philip</id>
      <name>Philip Helger</name>
      <email>ph(at)helger.com</email>
      <url>https://www.helger.com</url>
    </developer>
    <developer>
      <name>Sam Stevens</name>
      <email>samdjstevens(at)googlemail.com</email>
      <url>https://github.com/samdjstevens</url>
      <roles>
        <role>Original author of upstream java-totp</role>
      </roles>
    </developer>
  </developers>

  <properties>
    <commons-codec.version>1.22.1</commons-codec.version>
    <commons-net.version>3.13.0</commons-net.version>
    <jspecify.version>1.0.1</jspecify.version>
    <zxing.version>3.5.4</zxing.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.helger</groupId>
        <artifactId>ph-totp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.helger</groupId>
        <artifactId>ph-totp-qrcode</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>org.jspecify</groupId>
        <artifactId>jspecify</artifactId>
        <version>${jspecify.version}</version>
      </dependency>
      <dependency>
        <groupId>commons-codec</groupId>
        <artifactId>commons-codec</artifactId>
        <version>${commons-codec.version}</version>
      </dependency>
      <dependency>
        <groupId>commons-net</groupId>
        <artifactId>commons-net</artifactId>
        <version>${commons-net.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <modules>
    <module>ph-totp</module>
    <module>ph-totp-qrcode</module>
  </modules>
</project>
